import { Noto_Serif } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Topbar from '../components/Topbar'
import Footer from '../components/Footer'

const noto_serif = Noto_Serif({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto_serif.className} suppressHydrationWarning={true}>
      <Topbar/>
      {/* <Navbar/> */}
      {children}
      <Footer/>
      </body>
    </html>
  )
}
